classdecl    ->  "class" conid "(" varid ")" [ given ] "{" sig , ... "}"
instancedecl ->  "instance" varid ":" conid "(" type ")" [ given ]
                   "{" fundecl , ... "}"
sig          ->  varid ":" type

effectdecl   ->  "effect" conid [ tyvars ] "{" effop , ... "}"
effop        ->  "ctl" varid "(" [ type , ... ] ")" ":" type
errordecl    ->  "error" conid [ "(" type , ... ")" ]

patterndecl  ->  "pattern" conid "(" [ varid , ... ] ")" "for" conid "="
                   "view" expr [ "make" expr ]
