//! Single source of truth for the C runtime symbols codegen calls by name.
//!
//! These are the `prism_*` intrinsics defined in the `runtime/` C modules that the
//! emitter references directly: allocation, reference counting, boxing, the IO
//! ops, local mutable refs, the bignum arithmetic helpers, and the effect-machine
//! instrumentation. Spelling each as a named constant here (rather than a string
//! literal scattered across the emitter) means a rename happens in one place, and
//! the drift guard below pins every name to a definition in the runtime so a
//! mismatch fails the build instead of the linker.
//!
//! The surface builtins (`concat`, `show_int`, the fixed-width arithmetic, ...)
//! are not here: their symbols are derived once from [`crate::core::builtins::Builtin::sym`].
//!
//! This module also owns the embedded copy of the runtime. `build.rs` holds the
//! one canonical list of runtime files and generates a manifest of `(name, text,
//! is_header)` tuples ([`RUNTIME_FILES`]); the native link path writes those files
//! and compiles the sources ([`write_runtime`]), so the in-binary runtime and the
//! build-script-compiled runtime derive from the same list and cannot drift.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

// The runtime file table, generated by build.rs from its canonical source list.
include!(concat!(env!("OUT_DIR"), "/runtime_manifest.rs"));

/// Write every runtime file into `dir` for the C compiler.
///
/// Returns the absolute paths of the `.c` translation units to hand to the
/// compile step. The headers land beside the sources so each
/// `#include "prism_*.h"` resolves.
///
/// # Errors
/// Fails on any filesystem error creating `dir` or writing a runtime file.
#[cfg(feature = "native")]
pub fn write_runtime(dir: &Path) -> io::Result<Vec<PathBuf>> {
    fs::create_dir_all(dir)?;
    let mut sources = Vec::new();
    for (name, body, is_header) in RUNTIME_FILES {
        let path = dir.join(name);
        // Vendored libm files carry a `libm/` prefix; create the subdirectory so
        // the write lands and each `#include "libm.h"` resolves beside them.
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&path, body)?;
        if !is_header {
            sources.push(path);
        }
    }
    Ok(sources)
}

// Allocation and reference counting.
pub(super) const ALLOC: &str = "prism_alloc";
pub(super) const REUSE_ALLOC: &str = "prism_reuse_alloc";
pub(super) const REUSE_TOKEN: &str = "prism_reuse_token";
pub(super) const RC_INC: &str = "prism_rc_inc";
pub(super) const RC_DEC: &str = "prism_rc_dec";

// Tagging: box/unbox a 63-bit payload, and the interned string-literal cell.
pub(super) const BOX: &str = "prism_box";
pub(super) const UNBOX: &str = "prism_unbox";
pub(super) const STR_LIT: &str = "prism_str_lit";

// IO intrinsics (the lowered forms of `Comp::Io`).
pub(super) const PRINT_INT: &str = "prism_print_int";
pub(super) const PRINT_FLOAT: &str = "prism_print_float";
pub(super) const PRINT_NL: &str = "prism_print_nl";
pub(super) const READ_INT: &str = "prism_prim_read_int";
pub(super) const READ_LINE: &str = "prism_prim_read_line";
pub(super) const RAND: &str = "prism_prim_rand";
pub(super) const SRAND: &str = "prism_srand";
pub(super) const FATAL: &str = "prism_fatal";
pub(super) const ERROR_INT: &str = "prism_error_int";

// Local mutable cells (the runtime form of an escape-checked `var`).
pub(super) const REF_NEW: &str = "prism_ref_new";
pub(super) const REF_GET: &str = "prism_ref_get";
pub(super) const REF_SET: &str = "prism_ref_set";

// Bignum arithmetic, the slow path of the tagged-int operators.
pub(super) const INT_ADD: &str = "prism_rt_int_add";
pub(super) const INT_SUB: &str = "prism_rt_int_sub";
pub(super) const INT_MUL: &str = "prism_rt_int_mul";
pub(super) const INT_DIV: &str = "prism_rt_int_div";
pub(super) const INT_REM: &str = "prism_rt_int_rem";
pub(super) const INT_CMP: &str = "prism_rt_int_cmp";

// Canonicalize a raw i64 into an `Int`: a tagged immediate when it fits 63 bits,
// a bignum cell otherwise. The float->int conversions saturate to the full i64
// range (matching the interpreter's `f as i64`), and i64::MAX/MIN overflow the
// 63-bit tag, so the result must promote here rather than be inline-retagged.
pub(super) const INT_OF_LONG: &str = "prism_int_of_long";

// Effect-machine instrumentation and the two miscompile traps: the
// over-application trap and the non-exhaustive-`case` trap.
pub(super) const EFFOP_ALLOC: &str = "prism_effop_alloc";
pub(super) const DRIVE_STEP: &str = "prism_drive_step";
pub(super) const APPLY_ERROR: &str = "prism_apply_error";
pub(super) const MATCH_ERROR: &str = "prism_match_error";

// Every runtime symbol named above, for the drift guard.
#[cfg(test)]
const ALL: &[&str] = &[
    ALLOC,
    REUSE_ALLOC,
    REUSE_TOKEN,
    RC_INC,
    RC_DEC,
    BOX,
    UNBOX,
    STR_LIT,
    PRINT_INT,
    PRINT_FLOAT,
    PRINT_NL,
    READ_INT,
    READ_LINE,
    RAND,
    SRAND,
    FATAL,
    ERROR_INT,
    REF_NEW,
    REF_GET,
    REF_SET,
    INT_ADD,
    INT_SUB,
    INT_MUL,
    INT_DIV,
    INT_REM,
    INT_CMP,
    INT_OF_LONG,
    EFFOP_ALLOC,
    DRIVE_STEP,
    APPLY_ERROR,
    MATCH_ERROR,
];

#[cfg(test)]
mod tests {
    use super::ALL;

    // Every runtime symbol the emitter calls must be defined in the C runtime.
    // A rename on one side without the other would otherwise surface only as a
    // link failure (or, worse, a call to a stale symbol); this turns it into a
    // build failure naming the offender.
    #[test]
    fn symbols_defined_in_runtime() {
        for sym in ALL {
            let defined = super::RUNTIME_FILES
                .iter()
                .any(|(_, body, _)| body.contains(sym));
            assert!(
                defined,
                "runtime symbol `{sym}` (codegen::rt) is not defined in any runtime/ module"
            );
        }
    }
}
