//! Single source of truth for the C runtime symbols codegen calls by name.
//!
//! These are the `prism_*` intrinsics defined in the `runtime/` C modules that the
//! emitter references directly: allocation, reference counting, boxing, the IO
//! ops, local mutable refs, the bignum arithmetic helpers, and the effect-machine
//! instrumentation. Spelling each as a named constant here (rather than a string
//! literal scattered across the emitter) means a rename happens in one place, and
//! the drift guard below pins every name to a definition in the runtime so a
//! mismatch fails the build instead of the linker.
//!
//! The surface builtins (`concat`, `show_int`, the fixed-width arithmetic, ...)
//! are not here: their symbols are derived once from [`crate::core::builtins::Builtin::sym`].
//!
//! This module also owns the embedded copy of the runtime. `build.rs` holds the
//! one canonical file manifest; this module turns that manifest into typed
//! runtime profiles so optional subsystems are linked only by callers that
//! explicitly request them.

use std::fs;
use std::io;
use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use super::native_kont;

// The runtime file table, generated by build.rs from its canonical source list.
include!(concat!(env!("OUT_DIR"), "/runtime_manifest.rs"));

const PRISM_INTERNAL_H: &str = "prism_internal.h";
const PRISM_ARENA_H: &str = "prism_arena.h";
const PRISM_ARENA_C: &str = "prism_arena.c";
const PRISM_MEM_H: &str = "prism_mem.h";
const PRISM_MEM_C: &str = "prism_mem.c";
const PRISM_STRING_H: &str = "prism_string.h";
const PRISM_STRING_C: &str = "prism_string.c";
const PRISM_INT_H: &str = "prism_int.h";
const PRISM_INT_C: &str = "prism_int.c";
const PRISM_FLOAT_H: &str = "prism_float.h";
const PRISM_FLOAT_C: &str = "prism_float.c";
const PRISM_LIBM_H: &str = "prism_libm.h";
const PRISM_LIBM_RENAME_H: &str = "prism_libm_rename.h";
const PRISM_LIBM_C: &str = "prism_libm.c";
const PRISM_EFFECT_H: &str = "prism_effect.h";
const PRISM_EFFECT_C: &str = "prism_effect.c";
const PRISM_ARRAY_H: &str = "prism_array.h";
const PRISM_ARRAY_C: &str = "prism_array.c";
const PRISM_BUFFER_H: &str = "prism_buffer.h";
const PRISM_BUFFER_C: &str = "prism_buffer.c";
const PRISM_TBUF_H: &str = "prism_tbuf.h";
const PRISM_TBUF_C: &str = "prism_tbuf.c";
const PRISM_SIMD_H: &str = "prism_simd.h";
const PRISM_SIMD_C: &str = "prism_simd.c";
const PRISM_SORT_H: &str = "prism_sort.h";
const PRISM_SORT_C: &str = "prism_sort.c";
const PRISM_KONT_H: &str = "prism_kont.h";
const PRISM_KONT_C: &str = "prism_kont.c";
const PRISM_IO_H: &str = "prism_io.h";
const PRISM_IO_C: &str = "prism_io.c";

const BASE_RUNTIME_MODULES: &[RuntimeModule] = &[
    RuntimeModule::Memory,
    RuntimeModule::String,
    RuntimeModule::Integer,
    RuntimeModule::Float,
    RuntimeModule::LibmBridge,
    RuntimeModule::Effect,
    RuntimeModule::Sort,
    RuntimeModule::Array,
    RuntimeModule::Buffer,
    RuntimeModule::TypedBuffer,
    RuntimeModule::Simd,
    RuntimeModule::Io,
];
const NATIVE_RUNTIME_MODULES: &[RuntimeModule] = &[
    RuntimeModule::Memory,
    RuntimeModule::String,
    RuntimeModule::Integer,
    RuntimeModule::Float,
    RuntimeModule::LibmBridge,
    RuntimeModule::Effect,
    RuntimeModule::Sort,
    RuntimeModule::Array,
    RuntimeModule::Buffer,
    RuntimeModule::TypedBuffer,
    RuntimeModule::Simd,
    RuntimeModule::NativeKont,
    RuntimeModule::Io,
];

/// Runtime profile requested by a caller.
///
/// Host oracles need the core runtime and libm bridge, but not native
/// continuation metadata. Native backend links include the full runtime surface.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RuntimeProfile {
    HostOracle,
    NativeBackend,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum RuntimeModule {
    Memory,
    String,
    Integer,
    Float,
    LibmBridge,
    Effect,
    Sort,
    Array,
    Buffer,
    TypedBuffer,
    Simd,
    NativeKont,
    Io,
}

impl RuntimeProfile {
    const fn modules(self) -> &'static [RuntimeModule] {
        match self {
            Self::HostOracle => BASE_RUNTIME_MODULES,
            Self::NativeBackend => NATIVE_RUNTIME_MODULES,
        }
    }
}

impl RuntimeModule {
    const fn files(self) -> &'static [&'static str] {
        match self {
            // The region substrate rides with the memory core: prism_mem.c owns
            // the `with_arena` region policy over the prism_arena.h seam.
            Self::Memory => &[
                PRISM_INTERNAL_H,
                PRISM_ARENA_H,
                PRISM_ARENA_C,
                PRISM_MEM_H,
                PRISM_MEM_C,
            ],
            Self::String => &[PRISM_STRING_H, PRISM_STRING_C],
            Self::Integer => &[PRISM_INT_H, PRISM_INT_C],
            Self::Float => &[PRISM_FLOAT_H, PRISM_FLOAT_C],
            Self::LibmBridge => &[PRISM_LIBM_H, PRISM_LIBM_RENAME_H, PRISM_LIBM_C],
            Self::Effect => &[PRISM_EFFECT_H, PRISM_EFFECT_C],
            Self::Sort => &[PRISM_SORT_H, PRISM_SORT_C],
            Self::Array => &[PRISM_ARRAY_H, PRISM_ARRAY_C],
            Self::Buffer => &[PRISM_BUFFER_H, PRISM_BUFFER_C],
            Self::TypedBuffer => &[PRISM_TBUF_H, PRISM_TBUF_C],
            Self::Simd => &[PRISM_SIMD_H, PRISM_SIMD_C],
            Self::NativeKont => &[PRISM_KONT_H, PRISM_KONT_C],
            Self::Io => &[PRISM_IO_H, PRISM_IO_C],
        }
    }
}

fn runtime_entry(name: &str) -> io::Result<(&'static str, bool)> {
    RUNTIME_FILES
        .iter()
        .find_map(|(entry_name, body, is_header)| {
            (*entry_name == name).then_some((*body, *is_header))
        })
        .ok_or_else(|| {
            io::Error::new(
                ErrorKind::InvalidData,
                format!("runtime manifest is missing `{name}`"),
            )
        })
}

/// Write the native-backend runtime profile into `dir` for the C compiler.
///
/// Returns the absolute paths of the `.c` translation units to hand to the
/// compile step. The headers land beside the sources so each
/// `#include "prism_*.h"` resolves.
///
/// # Errors
/// Fails on any filesystem error creating `dir` or writing a runtime file.
#[cfg(feature = "native")]
pub fn write_runtime(dir: &Path) -> io::Result<Vec<PathBuf>> {
    write_runtime_for(dir, RuntimeProfile::NativeBackend)
}

/// Content digest of every runtime input selected by `profile`.
///
/// Native artifact queries include this so a runtime-only edit cannot reuse a
/// binary linked against stale runtime bytes.
///
/// # Panics
/// Panics if the compiler's static runtime manifest names a missing source file.
#[cfg(feature = "native")]
#[must_use]
pub fn runtime_profile_digest(profile: RuntimeProfile) -> String {
    let mut hasher = blake3::Hasher::new();
    for module in profile.modules() {
        for name in module.files() {
            hasher.update(&(name.len() as u64).to_le_bytes());
            hasher.update(name.as_bytes());
            let (body, _) =
                runtime_entry(name).expect("runtime profile file missing from manifest");
            hasher.update(&(body.len() as u64).to_le_bytes());
            hasher.update(body.as_bytes());
        }
    }
    hasher.update(&(LIBM_ARCHIVE.len() as u64).to_le_bytes());
    hasher.update(LIBM_ARCHIVE);
    hasher.finalize().to_hex().to_string()
}

/// Write the selected runtime profile into `dir` for the C compiler.
///
/// # Errors
/// Fails on any filesystem error, or if the generated runtime manifest omits a
/// file named by the selected profile.
#[cfg(feature = "native")]
pub fn write_runtime_for(dir: &Path, profile: RuntimeProfile) -> io::Result<Vec<PathBuf>> {
    fs::create_dir_all(dir)?;
    let mut sources = Vec::new();
    for module in profile.modules() {
        for name in module.files() {
            let (body, is_header) = runtime_entry(name)?;
            let path = dir.join(name);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(&path, body)?;
            if !is_header {
                sources.push(path);
            }
        }
    }
    Ok(sources)
}

/// The single vendored-libm archive, compiled exactly once by build.rs.
///
/// Embedded here so both the interpreter (which links it at build time) and every
/// native binary (via [`write_libm_archive`] + the link step) use THESE bytes, and
/// the non-correctly-rounded transcendentals stay bit-identical across backends. A
/// second, differently-invoked recompile is what let them drift by a ULP.
#[cfg(feature = "native")]
pub const LIBM_ARCHIVE: &[u8] = include_bytes!(env!("PRISM_LIBM_ARCHIVE"));

/// Materialize the embedded libm archive into `dir` and return its path, for the
/// native link step to link directly instead of recompiling the libm sources.
///
/// # Errors
/// Fails on any filesystem error writing the archive.
#[cfg(feature = "native")]
pub fn write_libm_archive(dir: &Path) -> io::Result<PathBuf> {
    let path = dir.join("libprism_libm.a");
    fs::write(&path, LIBM_ARCHIVE)?;
    Ok(path)
}

// Allocation and reference counting.
pub(super) const ALLOC: &str = "prism_alloc";
pub(super) const REUSE_ALLOC: &str = "prism_reuse_alloc";
pub(super) const REUSE_TOKEN: &str = "prism_reuse_token";
pub(super) const RC_INC: &str = "prism_rc_inc";
pub(super) const RC_DEC: &str = "prism_rc_dec";

// Tagging: box/unbox a 63-bit payload, and the interned string-literal cell.
pub(super) const BOX: &str = "prism_box";
pub(super) const UNBOX: &str = "prism_unbox";
pub(super) const STR_LIT: &str = "prism_str_lit";

// IO intrinsics (the lowered forms of `Comp::Io`).
pub(super) const PRINT_INT: &str = "prism_print_int";
pub(super) const PRINT_FLOAT: &str = "prism_print_float";
pub(super) const PRINT_NL: &str = "prism_print_nl";
pub(super) const READ_INT: &str = "prism_prim_read_int";
pub(super) const READ_LINE: &str = "prism_prim_read_line";
pub(super) const RAND: &str = "prism_prim_rand";
pub(super) const SRAND: &str = "prism_srand";
pub(super) const FATAL: &str = "prism_fatal";
pub(super) const ERROR_INT: &str = "prism_error_int";

// Local mutable cells (the runtime form of an escape-checked `var`).
pub(super) const REF_NEW: &str = "prism_ref_new";
pub(super) const REF_GET: &str = "prism_ref_get";
pub(super) const REF_SET: &str = "prism_ref_set";

// Bignum arithmetic, the slow path of the tagged-int operators.
pub(super) const INT_ADD: &str = "prism_rt_int_add";
pub(super) const INT_SUB: &str = "prism_rt_int_sub";
pub(super) const INT_MUL: &str = "prism_rt_int_mul";
pub(super) const INT_DIV: &str = "prism_rt_int_div";
pub(super) const INT_REM: &str = "prism_rt_int_rem";
pub(super) const INT_CMP: &str = "prism_rt_int_cmp";

// Canonicalize a raw i64 into an `Int`: a tagged immediate when it fits 63 bits,
// a bignum cell otherwise. The float->int conversions saturate to the full i64
// range (matching the interpreter's `f as i64`), and i64::MAX/MIN overflow the
// 63-bit tag, so the result must promote here rather than be inline-retagged.
pub(super) const INT_OF_LONG: &str = "prism_int_of_long";

// Effect-machine instrumentation and the two miscompile traps: the
// over-application trap and the non-exhaustive-`case` trap.
pub(super) const EFFOP_ALLOC: &str = "prism_effop_alloc";
pub(super) const DRIVE_STEP: &str = "prism_drive_step";
pub(super) const APPLY_ERROR: &str = "prism_apply_error";
pub(super) const MATCH_ERROR: &str = "prism_match_error";

// Native kont shadow-state instrumentation.
pub(super) const NATIVE_KONT_ENTER: &str = native_kont::ENTER_SYMBOL;
pub(super) const NATIVE_KONT_ARG: &str = native_kont::ARG_SYMBOL;
pub(super) const NATIVE_KONT_TAILCALL: &str = native_kont::TAILCALL_SYMBOL;
pub(super) const NATIVE_KONT_LEAVE: &str = native_kont::LEAVE_SYMBOL;

// Every runtime symbol named above, for the drift guard.
#[cfg(test)]
const ALL: &[&str] = &[
    ALLOC,
    REUSE_ALLOC,
    REUSE_TOKEN,
    RC_INC,
    RC_DEC,
    BOX,
    UNBOX,
    STR_LIT,
    PRINT_INT,
    PRINT_FLOAT,
    PRINT_NL,
    READ_INT,
    READ_LINE,
    RAND,
    SRAND,
    FATAL,
    ERROR_INT,
    REF_NEW,
    REF_GET,
    REF_SET,
    INT_ADD,
    INT_SUB,
    INT_MUL,
    INT_DIV,
    INT_REM,
    INT_CMP,
    INT_OF_LONG,
    EFFOP_ALLOC,
    DRIVE_STEP,
    APPLY_ERROR,
    MATCH_ERROR,
    NATIVE_KONT_ENTER,
    NATIVE_KONT_ARG,
    NATIVE_KONT_TAILCALL,
    NATIVE_KONT_LEAVE,
];

#[cfg(test)]
mod tests {
    #[cfg(feature = "native")]
    use std::process::Command;
    #[cfg(feature = "native")]
    use std::sync::atomic::{AtomicU64, Ordering};

    use super::super::mangle::{SYM_NAMESPACE, SYM_RUNTIME};
    use super::super::MAIN_SYMBOL;
    use super::{native_kont, ALL};

    const KONT_RUNTIME_FILES: &[&str] = &["prism_kont.h", "prism_kont.c"];
    const KONT_TEST_SCHEME: &str = "prism-core-hash-v1";
    const KONT_TEST_BUNDLE: &str = "0123456789abcdef";
    const KONT_TEST_HASH: &str = "9d18022b96cb1349a4de4ab500879606121e86d736be1fc2da3f69385c9fcd35";
    const KONT_TEST_SYMBOL: &str = super::super::MAIN_SYMBOL;
    const KONT_TEST_CORE_NAME: &str = crate::names::ENTRY_POINT;
    const KONT_LOOKUP_HARNESS: &str = include_str!("../../tests/fixtures/native_kont_lookup.c");
    const KONT_HARNESS_REPLACEMENTS: [(&str, &str); 5] = [
        ("@KONT_TEST_SCHEME@", KONT_TEST_SCHEME),
        ("@KONT_TEST_BUNDLE@", KONT_TEST_BUNDLE),
        ("@KONT_TEST_HASH@", KONT_TEST_HASH),
        ("@KONT_TEST_SYMBOL@", KONT_TEST_SYMBOL),
        ("@KONT_TEST_CORE_NAME@", KONT_TEST_CORE_NAME),
    ];
    #[cfg(feature = "native")]
    static KONT_TEST_SEQ: AtomicU64 = AtomicU64::new(0);

    fn kont_lookup_harness() -> String {
        let mut body = KONT_LOOKUP_HARNESS.to_string();
        for (needle, replacement) in KONT_HARNESS_REPLACEMENTS {
            body = body.replace(needle, replacement);
        }
        body
    }

    // Every runtime symbol the emitter calls must be defined in the C runtime.
    // A rename on one side without the other would otherwise surface only as a
    // link failure (or, worse, a call to a stale symbol); this turns it into a
    // build failure naming the offender.
    #[test]
    fn symbols_defined_in_runtime() {
        for sym in ALL {
            let defined = super::RUNTIME_FILES
                .iter()
                .any(|(_, body, _)| body.contains(sym));
            assert!(
                defined,
                "runtime symbol `{sym}` (codegen::rt) is not defined in any runtime/ module"
            );
        }
    }

    // Blank out comments and string/char literals so the namespace scan below
    // reads code rather than prose: a comment naming a codegen symbol is not a
    // definition of one, and `#include "prism_io.h"` is not a symbol at all.
    fn code_only(src: &str) -> String {
        let bytes = src.as_bytes();
        let mut out = String::with_capacity(src.len());
        let mut i = 0;
        while i < bytes.len() {
            match bytes[i] {
                b'/' if bytes.get(i + 1) == Some(&b'*') => {
                    i += 2;
                    while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                        i += 1;
                    }
                    i = (i + 2).min(bytes.len());
                    out.push(' ');
                }
                b'/' if bytes.get(i + 1) == Some(&b'/') => {
                    while i < bytes.len() && bytes[i] != b'\n' {
                        i += 1;
                    }
                    out.push(' ');
                }
                quote @ (b'"' | b'\'') => {
                    i += 1;
                    while i < bytes.len() && bytes[i] != quote {
                        i += usize::from(bytes[i] == b'\\') + 1;
                    }
                    i += 1;
                    out.push(' ');
                }
                c => {
                    out.push(if c.is_ascii() { c as char } else { ' ' });
                    i += 1;
                }
            }
        }
        out
    }

    // Every identifier in `code` that opens the `prism` namespace, i.e. is not
    // merely the tail of some longer unrelated name.
    fn namespace_idents(code: &str) -> Vec<&str> {
        let bytes = code.as_bytes();
        let ident_byte = |b: u8| b.is_ascii_alphanumeric() || b == b'_';
        code.match_indices(SYM_NAMESPACE)
            .filter(|(i, _)| *i == 0 || !ident_byte(bytes[i - 1]))
            .map(|(i, _)| {
                let mut end = i;
                while end < bytes.len() && ident_byte(bytes[end]) {
                    end += 1;
                }
                &code[i..end]
            })
            .collect()
    }

    // The reverse of `symbols_defined_in_runtime`, and the invariant that keeps a
    // user function named after a runtime intrinsic (`bump`, `alloc`, `box`) from
    // colliding with it: user and codegen names are minted into namespaces that
    // differ from the runtime's at index 5, so this holds as long as the runtime
    // stays entirely inside `prism_`. Checking it here makes a stray runtime
    // symbol a build failure instead of a duplicate-symbol link error in whatever
    // user program happens to pick the same name.
    #[test]
    fn runtime_defines_nothing_in_a_codegen_namespace() {
        for (file, body, _) in super::RUNTIME_FILES {
            for ident in namespace_idents(&code_only(body)) {
                // The sole deliberate crossing: the runtime's `main` calls the
                // user's entry point, which lives in the Core-function namespace.
                if ident == MAIN_SYMBOL {
                    continue;
                }
                assert!(
                    ident.starts_with(SYM_RUNTIME),
                    "runtime/{file} names `{ident}`, which is outside the runtime's \
                     `{SYM_RUNTIME}` namespace; a user function could spell it and \
                     collide at link time"
                );
            }
        }
    }

    #[test]
    fn native_kont_runtime_surface_is_manifested() {
        for file in KONT_RUNTIME_FILES {
            assert!(
                super::RUNTIME_FILES.iter().any(|(name, _, _)| name == file),
                "runtime kont file `{file}` is missing from the embedded runtime manifest"
            );
        }
        for sym in native_kont::RUNTIME_SURFACE_SYMBOLS {
            let defined = super::RUNTIME_FILES
                .iter()
                .any(|(_, body, _)| body.contains(sym));
            assert!(
                defined,
                "native kont runtime symbol `{sym}` is not defined in any runtime/ module"
            );
        }
    }

    #[cfg(all(feature = "native", not(target_arch = "wasm32")))]
    fn run_kont_lookup_harness(extra_cflags: &[&str]) {
        let cc = std::env::var("PRISM_CC").unwrap_or_else(|_| env!("PRISM_BUILD_CC").into());
        if !Command::new(&cc)
            .arg("--version")
            .output()
            .is_ok_and(|o| o.status.success())
        {
            eprintln!("skipping native kont runtime lookup: C compiler `{cc}` not found");
            return;
        }

        let stem = format!(
            "prism_kont_lookup_{}_{}",
            std::process::id(),
            KONT_TEST_SEQ.fetch_add(1, Ordering::Relaxed)
        );
        let dir = std::env::temp_dir().join(&stem);
        std::fs::create_dir_all(&dir).unwrap();
        let rt_sources = super::write_runtime(&dir).unwrap();
        let libm_archive = super::write_libm_archive(&dir).unwrap();
        let src = dir.join(format!("{stem}.c"));
        let bin = dir.join(&stem);
        std::fs::write(&src, kont_lookup_harness()).unwrap();
        let mut cmd = Command::new(&cc);
        cmd.args(["-O0", "-w", "-DPRISM_NATIVE_KONT_FRAMES"]);
        if cfg!(target_os = "linux") {
            cmd.arg("-rdynamic");
        }
        let comp = cmd
            .args(extra_cflags)
            .arg(&src)
            .args(&rt_sources)
            .arg(&libm_archive)
            .arg("-o")
            .arg(&bin)
            .output()
            .unwrap();
        assert!(
            comp.status.success(),
            "native kont runtime lookup harness failed to compile:\n{}",
            String::from_utf8_lossy(&comp.stderr)
        );
        let run = Command::new(&bin).output().unwrap();
        let _ = std::fs::remove_dir_all(&dir);
        assert!(
            run.status.success(),
            "native kont runtime lookup harness exited with {:?}\nstdout:\n{}\nstderr:\n{}",
            run.status,
            String::from_utf8_lossy(&run.stdout),
            String::from_utf8_lossy(&run.stderr)
        );
    }

    // Hostile-input harness for the arena region policy: refcount traffic
    // against arena-owned cells, escape promotion over shared/DAG/deep shapes,
    // cross-region references, child release at destruction, and the
    // unbalanced-bracket trap, driven directly against the materialized
    // runtime (see tests/fixtures/arena_hostile.c). Honors PRISM_CC_FLAGS so a
    // sanitizer environment sweeps it too.
    #[cfg(all(feature = "native", not(target_arch = "wasm32")))]
    #[test]
    fn arena_region_hostile_harness() {
        const ARENA_HARNESS: &str = include_str!("../../tests/fixtures/arena_hostile.c");
        let cc = std::env::var("PRISM_CC").unwrap_or_else(|_| env!("PRISM_BUILD_CC").into());
        if !Command::new(&cc)
            .arg("--version")
            .output()
            .is_ok_and(|o| o.status.success())
        {
            eprintln!("skipping arena hostile harness: C compiler `{cc}` not found");
            return;
        }
        let stem = format!(
            "prism_arena_hostile_{}_{}",
            std::process::id(),
            KONT_TEST_SEQ.fetch_add(1, Ordering::Relaxed)
        );
        let dir = std::env::temp_dir().join(&stem);
        std::fs::create_dir_all(&dir).unwrap();
        // The host-oracle profile: the harness drives the memory core directly
        // and needs no native kont tables (which only generated programs
        // define).
        let rt_sources = super::write_runtime_for(&dir, super::RuntimeProfile::HostOracle).unwrap();
        let libm_archive = super::write_libm_archive(&dir).unwrap();
        let src = dir.join(format!("{stem}.c"));
        let bin = dir.join(&stem);
        std::fs::write(&src, ARENA_HARNESS).unwrap();
        let mut cmd = Command::new(&cc);
        cmd.args(["-O1", "-w"]);
        if let Ok(flags) = std::env::var("PRISM_CC_FLAGS") {
            cmd.args(flags.split_whitespace());
        }
        let comp = cmd
            .arg(&src)
            .args(&rt_sources)
            .arg(&libm_archive)
            .arg("-o")
            .arg(&bin)
            .output()
            .unwrap();
        assert!(
            comp.status.success(),
            "arena hostile harness failed to compile:\n{}",
            String::from_utf8_lossy(&comp.stderr)
        );
        let run = Command::new(&bin).output().unwrap();
        let _ = std::fs::remove_dir_all(&dir);
        assert!(
            run.status.success(),
            "arena hostile harness exited with {:?}\nstdout:\n{}\nstderr:\n{}",
            run.status,
            String::from_utf8_lossy(&run.stdout),
            String::from_utf8_lossy(&run.stderr)
        );
    }

    #[cfg(all(feature = "native", not(target_arch = "wasm32")))]
    #[test]
    fn native_kont_runtime_lookup_reads_embedded_table() {
        run_kont_lookup_harness(&[]);
    }

    #[cfg(all(feature = "native", not(target_arch = "wasm32")))]
    #[test]
    fn native_kont_runtime_refuses_missing_pointer_table() {
        run_kont_lookup_harness(&["-DPRISM_KONT_NO_PTR_TABLE"]);
    }
}
