use std::collections::BTreeMap;

use prism_core::types::{CtorInfo, Type};
use prism_syntax::kw;

// The scalar-literal encoding plan is a fact of the representation authority,
// shared with the reference-count and borrow passes; codegen re-exports it so
// emission arms and their guard have one import home.
pub(crate) use prism_core::types::{scalar_plan, ScalarPlan};

// The runtime's cell layout and reserved heap-tag family, generated by
// build.rs from runtime/prism_internal.h so this mirror cannot drift from the
// C: TAG_OFF, HDR_BYTES, WORD_BYTES, one named constant per PRISM_*_TAG, and
// RESERVED_HEAP_TAGS pairing each tag with its C define name.
include!(concat!(env!("OUT_DIR"), "/runtime_abi.rs"));

/// The native word for the wired nullable's `Null`: the machine zero word.
/// `This(v)` is its element word unchanged, so the type allocates no cell on
/// the native tiers; the element contract (`types::is_or_null_element`) proves
/// no admitted element can ever be this word.
pub(crate) const NULL_WORD: i64 = 0;

// Null-word dispatch derives the case tag as `zext(word != 0)`; that identity
// is only correct while the wired tags are exactly `Null = 0` / `This = 1`.
const _: () = assert!(kw::OR_NULL_TAG == 0 && kw::OR_THIS_TAG == 1);

const _: () = assert!(
    size_of::<usize>() == 8 && size_of::<u64>() == 8,
    "prism tagging scheme assumes LP64"
);

pub(crate) fn idx64(n: usize) -> i64 {
    i64::try_from(n).unwrap_or(i64::MAX)
}

/// Byte offset of field slot `index` inside a heap cell: the header, then one
/// word per preceding slot. Constructor fields, boxed tuple fields, and
/// closure captures each occupy exactly one runtime word; the typed verifier
/// checks that invariant on every cell slot, so this fixed stride never needs
/// a per-slot layout consult.
pub(crate) fn field_slot_off(index: usize) -> i64 {
    HDR_BYTES + idx64(index) * WORD_BYTES
}

/// Guard one literal arm against representation drift: the arm names the
/// encoding it emits, and emission fails closed if the authority now plans a
/// different one.
pub(crate) fn require_scalar_plan(
    ty: &Type,
    expected: ScalarPlan,
    what: &str,
) -> Result<(), String> {
    let plan = scalar_plan(ty)?;
    if plan == expected {
        Ok(())
    } else {
        Err(format!(
            "codegen: {what} literal emits the {expected:?} encoding but the \
             layout authority plans {plan:?}"
        ))
    }
}

/// The runtime tag a `Case` dispatches on for constructor `name`: the wired-in
/// nullable's `Null`/`This` tags, otherwise the datatype table's tag. Keeps the
/// tag source the single `kw` constant instead of a literal re-typed in codegen.
pub(crate) fn ctor_tag(ctors: &BTreeMap<String, CtorInfo>, name: &str) -> Option<usize> {
    match name {
        kw::CTOR_NULL => Some(kw::OR_NULL_TAG),
        kw::CTOR_THIS => Some(kw::OR_THIS_TAG),
        _ => ctors.get(name).map(|info| info.tag),
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use prism_common::sym::Sym;
    use prism_core::core::{Comp, Core, CoreFn, LoweredCore, Value};
    use prism_core::types::{layout_of_type, AbiLayout, RcBehavior, Repr, Type};

    fn lowered_value(value: Value) -> LoweredCore {
        let core = Core {
            fns: vec![CoreFn {
                name: Sym::new("main"),
                params: Vec::new(),
                body: Comp::Return(value),
                dict_arity: 0,
            }],
        };
        LoweredCore::validate(core)
            .map_err(|violations| violations.join("\n"))
            .expect("test Core is structurally lowered")
    }

    fn emit_value(value: Value) -> String {
        crate::emit_llvm(&lowered_value(value), &BTreeMap::new()).expect("LLVM emission succeeds")
    }

    #[cfg(feature = "mlir")]
    fn emit_value_mlir(value: Value) -> String {
        crate::emit_mlir(&lowered_value(value), &BTreeMap::new()).expect("MLIR emission succeeds")
    }

    #[test]
    fn scalar_layout_matches_native_boxing() {
        for ty in [Type::I64, Type::U64, Type::Float] {
            let layout = layout_of_type(&ty);
            assert_eq!(layout.local(), &Repr::NonNullValue);
            assert_eq!(layout.abi(), &AbiLayout::Direct(Repr::NonNullValue));
            assert_eq!(layout.rc(), RcBehavior::Managed);
        }

        for (name, value) in [
            ("I64", Value::I64(7)),
            ("U64", Value::U64(9)),
            ("Float", Value::Float(1.5)),
        ] {
            let ir = emit_value(value.clone());
            assert!(
                ir.lines()
                    .any(|line| line.contains("call i64 @prism_box(i64")),
                "{name} emission must allocate the box promised by its layout"
            );
            #[cfg(feature = "mlir")]
            assert!(
                emit_value_mlir(value)
                    .lines()
                    .any(|line| line.contains("llvm.call @prism_box(")),
                "MLIR {name} emission must allocate the same box"
            );
        }
    }

    #[test]
    fn escaping_unboxed_product_uses_the_boxed_boundary_plan() {
        let layout = layout_of_type(&Type::UnboxedTuple(vec![Type::Int, Type::Bool]));
        assert!(matches!(layout.local(), Repr::Product(_)));
        assert_eq!(layout.abi(), &AbiLayout::BoxedProduct);
        assert_eq!(layout.abi().repr(), Some(Repr::NonNullValue));

        let ir = emit_value(Value::UnboxedTuple(vec![Value::Int(1), Value::Bool(true)]));
        assert!(
            ir.lines()
                .any(|line| line.contains("call ptr @prism_alloc(i64 2)")),
            "an escaping unboxed product must follow the boxed boundary plan"
        );
        #[cfg(feature = "mlir")]
        assert!(
            emit_value_mlir(Value::UnboxedTuple(vec![Value::Int(1), Value::Bool(true)]))
                .lines()
                .any(|line| line.contains("llvm.call @prism_alloc(")),
            "MLIR products must follow the same boxed boundary plan"
        );
    }
}
