#!/usr/bin/env python3
"""Fold per-case timing logs into the corpus shard weights.

A run with PRISM_CASE_TIMINGS=<file> appends `<label>\t<micros>` for every case
the corpus worker pool checks; CI uploads one such log per corpus-oracle shard
as a `case-timings-*` artifact. This sums each program's time over every log
given, in milliseconds, and writes tests/shard_weights.txt, which the test
harness reads to split the corpus into cost-balanced shards. Weights only steer
balance: the split is an exact cover whatever they say, so a stale file costs
wall time, never coverage.

    scripts/shard_weights.py LOG [LOG ...]
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEIGHTS = ROOT / "tests" / "shard_weights.txt"
HEADER = (
    "# Measured per-program corpus cost in milliseconds, summed over the\n"
    "# relations the logs cover. Generated by scripts/shard_weights.py; steers\n"
    "# shard balance only, never which programs run.\n"
)


def main(logs: list[str]) -> int:
    if not logs:
        print((__doc__ or "").strip(), file=sys.stderr)
        return 2
    micros: dict[str, int] = defaultdict(int)
    for log in logs:
        for line in Path(log).read_text().splitlines():
            label, _, value = line.partition("\t")
            if label and value.strip().isdigit():
                micros[label] += int(value)
    rows = "".join(
        f"{label}\t{max(1, total // 1000)}\n" for label, total in sorted(micros.items())
    )
    WEIGHTS.write_text(HEADER + rows)
    print(f"{WEIGHTS.relative_to(ROOT)}: {len(micros)} programs")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
