#!/usr/bin/env bash
# Regenerate the compact Lean differential-oracle fixture manifest.
#
# The live differential oracle feeds full `prism dump core-json` output into
# Lean at CI time. This manifest records the exact source fixture, generated Lean
# input, canonical Core identity, and expected result without committing
# line-exploding JSON.
#
# This is the `just hash` / `just docs-gen` idiom: the manifest is a committed
# artifact, and CI's drift check regenerates it and diffs (see the Lean job in
# .github/workflows/ci.yml). Run this whenever the compiler's core output or the
# fixtures change, and commit the result.
set -euo pipefail
cd "$(dirname "$0")"
PRISM="${PRISM:-../target/debug/prism}"
MANIFEST="fixtures/core-hashes.tsv"

FIXTURES=()
while IFS= read -r fixture; do
  FIXTURES+=("${fixture#fixtures/}")
done < <(find fixtures -maxdepth 1 -type f -name '*.pr' | sort)

hash_stdin() {
  python3 -c 'import hashlib, sys; print(hashlib.sha256(sys.stdin.buffer.read()).hexdigest())'
}

hash_file() {
  python3 -c 'import hashlib, pathlib, sys; print(hashlib.sha256(pathlib.Path(sys.argv[1]).read_bytes()).hexdigest())' "$1"
}

extract_main_hash() {
  awk '$2 == "main" { print $1; found = 1 } END { if (!found) exit 1 }'
}

render_value() {
  sed -n 's/^=> //p' | tail -n 1
}

tmp="$(mktemp "${TMPDIR:-/tmp}/prism-fixtures.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
{
  printf '# Generated by models/gen_fixtures.sh. Do not edit.\n'
  printf '# fixture\tsource-sha256\tdefs\tmain-core-hash\tcore-hash-list-sha256\tcore-json-sha256\tresult\n'
  for fixture in "${FIXTURES[@]}"; do
    name="${fixture%.pr}"
    path="fixtures/$fixture"
    source_hash="$(hash_file "$path")"
    core_hashes="$($PRISM dump core-hash "$path" 2>/dev/null)"
    core_json="$($PRISM dump core-json "$path" 2>/dev/null)"
    defs="$(printf '%s\n' "$core_hashes" | wc -l | tr -d ' ')"
    main_hash="$(printf '%s\n' "$core_hashes" | extract_main_hash)"
    core_hash_digest="$(printf '%s\n' "$core_hashes" | hash_stdin)"
    core_json_digest="$(printf '%s' "$core_json" | hash_stdin)"
    value="$($PRISM run "$path" 2>/dev/null | render_value)"
    if [ -z "$value" ]; then
      echo "gen_fixtures: prism run produced no final value for $name" >&2
      exit 1
    fi
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
      "$name" "$source_hash" "$defs" "$main_hash" "$core_hash_digest" "$core_json_digest" "$value"
  done
} > "$tmp"
mv "$tmp" "$MANIFEST"
echo "regenerated: $MANIFEST (${#FIXTURES[@]} fixtures)"
